// flow-typed signature: 8014a832b6aafe54b32301ba280097ed
// flow-typed version: <<STUB>>/reactfire_v^1.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactfire'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactfire' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactfire/dist/reactfire' {
  declare module.exports: any;
}

declare module 'reactfire/dist/reactfire.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactfire/dist/reactfire.js' {
  declare module.exports: $Exports<'reactfire/dist/reactfire'>;
}
declare module 'reactfire/dist/reactfire.min.js' {
  declare module.exports: $Exports<'reactfire/dist/reactfire.min'>;
}
