// flow-typed signature: c343d7edad981b9e20b8007f68c3c416
// flow-typed version: <<STUB>>/react-mixin_v^2.0.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mixin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mixin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-mixin/index' {
  declare module.exports: $Exports<'react-mixin'>;
}
declare module 'react-mixin/index.js' {
  declare module.exports: $Exports<'react-mixin'>;
}
