// flow-typed signature: dec19d167515fb1b5b5d33fcce0c7446
// flow-typed version: <<STUB>>/react-timer-mixin_v^0.13.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-timer-mixin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-timer-mixin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-timer-mixin/__tests__/TimerMixin-test' {
  declare module.exports: any;
}

declare module 'react-timer-mixin/TimerMixin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-timer-mixin/__tests__/TimerMixin-test.js' {
  declare module.exports: $Exports<'react-timer-mixin/__tests__/TimerMixin-test'>;
}
declare module 'react-timer-mixin/TimerMixin.js' {
  declare module.exports: $Exports<'react-timer-mixin/TimerMixin'>;
}
