// flow-typed signature: 604e0b736ce6b2fa59053855b21d5b91
// flow-typed version: <<STUB>>/riek_v^1.0.7/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'riek'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'riek' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'riek/demo/demo' {
  declare module.exports: any;
}

declare module 'riek/demo/demo' {
  declare module.exports: any;
}

declare module 'riek/lib/index' {
  declare module.exports: any;
}

declare module 'riek/lib/RIEBase' {
  declare module.exports: any;
}

declare module 'riek/lib/RIENumber' {
  declare module.exports: any;
}

declare module 'riek/lib/RIESelect' {
  declare module.exports: any;
}

declare module 'riek/lib/RIEStatefulBase' {
  declare module.exports: any;
}

declare module 'riek/lib/RIETags' {
  declare module.exports: any;
}

declare module 'riek/lib/RIETextArea' {
  declare module.exports: any;
}

declare module 'riek/lib/RIEToggle' {
  declare module.exports: any;
}

declare module 'riek/src/index' {
  declare module.exports: any;
}

declare module 'riek/src/RIEBase' {
  declare module.exports: any;
}

declare module 'riek/src/RIENumber' {
  declare module.exports: any;
}

declare module 'riek/src/RIESelect' {
  declare module.exports: any;
}

declare module 'riek/src/RIEStatefulBase' {
  declare module.exports: any;
}

declare module 'riek/src/RIETags' {
  declare module.exports: any;
}

declare module 'riek/src/RIETextArea' {
  declare module.exports: any;
}

declare module 'riek/src/RIEToggle' {
  declare module.exports: any;
}

declare module 'riek/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'riek/demo/demo.js' {
  declare module.exports: $Exports<'riek/demo/demo'>;
}
declare module 'riek/demo/demo.jsx' {
  declare module.exports: $Exports<'riek/demo/demo'>;
}
declare module 'riek/lib/index.js' {
  declare module.exports: $Exports<'riek/lib/index'>;
}
declare module 'riek/lib/RIEBase.js' {
  declare module.exports: $Exports<'riek/lib/RIEBase'>;
}
declare module 'riek/lib/RIENumber.js' {
  declare module.exports: $Exports<'riek/lib/RIENumber'>;
}
declare module 'riek/lib/RIESelect.js' {
  declare module.exports: $Exports<'riek/lib/RIESelect'>;
}
declare module 'riek/lib/RIEStatefulBase.js' {
  declare module.exports: $Exports<'riek/lib/RIEStatefulBase'>;
}
declare module 'riek/lib/RIETags.js' {
  declare module.exports: $Exports<'riek/lib/RIETags'>;
}
declare module 'riek/lib/RIETextArea.js' {
  declare module.exports: $Exports<'riek/lib/RIETextArea'>;
}
declare module 'riek/lib/RIEToggle.js' {
  declare module.exports: $Exports<'riek/lib/RIEToggle'>;
}
declare module 'riek/src/index.js' {
  declare module.exports: $Exports<'riek/src/index'>;
}
declare module 'riek/src/RIEBase.js' {
  declare module.exports: $Exports<'riek/src/RIEBase'>;
}
declare module 'riek/src/RIENumber.js' {
  declare module.exports: $Exports<'riek/src/RIENumber'>;
}
declare module 'riek/src/RIESelect.js' {
  declare module.exports: $Exports<'riek/src/RIESelect'>;
}
declare module 'riek/src/RIEStatefulBase.js' {
  declare module.exports: $Exports<'riek/src/RIEStatefulBase'>;
}
declare module 'riek/src/RIETags.js' {
  declare module.exports: $Exports<'riek/src/RIETags'>;
}
declare module 'riek/src/RIETextArea.js' {
  declare module.exports: $Exports<'riek/src/RIETextArea'>;
}
declare module 'riek/src/RIEToggle.js' {
  declare module.exports: $Exports<'riek/src/RIEToggle'>;
}
declare module 'riek/webpack.config.js' {
  declare module.exports: $Exports<'riek/webpack.config'>;
}
